import { type Button } from "./button";
import {
    add,
    divide,
    insertRight,
    multiply,
    negate,
    replace,
    reverse,
    deleteRight,
    exponent,
    subtract,
    sumDigits,
    cycleLeft,
    cycleRight,
    mirror,
    addButtonValue,
    store,
    inv10,
} from "./button_templates";

type Level = {
    initial: number;
    goal: number;
    moves: number;
    buttons: Button[];
    portalPos?: [number, number];
};

const LEVELS_SIMPLE_MACHINE: Level[] = [
    {
        initial: 0,
        goal: 2,
        moves: 2,
        buttons: [add(1)],
    },
    {
        initial: 0,
        goal: 8,
        moves: 3,
        buttons: [add(2), add(3)],
    },
    {
        initial: 0,
        goal: 12,
        moves: 3,
        buttons: [add(1), add(2), multiply(4)],
    },
    {
        initial: 1,
        goal: 7,
        moves: 3,
        buttons: [add(4), subtract(2)],
    },
    {
        initial: 0,
        goal: 20,
        moves: 3,
        buttons: [add(4), multiply(4)],
    },
    {
        initial: 0,
        goal: 40,
        moves: 4,
        buttons: [add(2), multiply(4)],
    },
    {
        initial: 100,
        goal: 10,
        moves: 4,
        buttons: [add(3), divide(5)],
    },
    {
        initial: 4321,
        goal: 4,
        moves: 3,
        buttons: [deleteRight()],
    },
    {
        initial: 0,
        goal: 4,
        moves: 3,
        buttons: [add(8), multiply(5), deleteRight()],
    },
    {
        initial: 50,
        goal: 9,
        moves: 4,
        buttons: [multiply(3), divide(5), deleteRight()],
    },
    {
        initial: 99,
        goal: 100,
        moves: 3,
        buttons: [subtract(8), multiply(11), deleteRight()],
    },

    {
        initial: 0,
        goal: 404,
        moves: 5,
        buttons: [add(8), multiply(10), divide(2)],
    },
    {
        initial: 171,
        goal: 23,
        moves: 4,
        buttons: [subtract(9), multiply(2), deleteRight()],
    },
    {
        initial: 0,
        goal: 21,
        moves: 5,
        buttons: [add(5), multiply(3), multiply(5), deleteRight()],
    },
    {
        initial: 10,
        goal: 50,
        moves: 3,
        buttons: [subtract(5), multiply(2), multiply(3)],
    },
    {
        initial: 0,
        goal: 2,
        moves: 5,
        buttons: [add(4), multiply(9), deleteRight()],
    },
    {
        initial: 0,
        goal: 11,
        moves: 2,
        buttons: [insertRight(1)],
    },
    {
        initial: 0,
        goal: 101,
        moves: 3,
        buttons: [insertRight(0), insertRight(1)],
    },
    {
        initial: 0,
        goal: 44,
        moves: 3,
        buttons: [multiply(2), insertRight(2)],
    },
    {
        initial: 0,
        goal: 35,
        moves: 2,
        buttons: [add(3), insertRight(5)],
    },
    {
        initial: 0,
        goal: 56,
        moves: 3,
        buttons: [add(5), insertRight(1)],
    },
    {
        initial: 0,
        goal: 9,
        moves: 4,
        buttons: [add(2), divide(3), insertRight(1)],
    },
    {
        initial: 15,
        goal: 10,
        moves: 4,
        buttons: [add(2), divide(5), insertRight(0)],
    },
    {
        initial: 0,
        goal: 210,
        moves: 5,
        buttons: [add(5), subtract(5), insertRight(2), insertRight(5)],
    },
    {
        initial: 40,
        goal: 2020,
        moves: 4,
        buttons: [add(4), divide(2), insertRight(0)],
    },
    {
        initial: 0,
        goal: 11,
        moves: 4,
        buttons: [insertRight(12), deleteRight()],
    },
    {
        initial: 0,
        goal: 102,
        moves: 4,
        buttons: [add(1), insertRight(10), deleteRight()],
    },
    {
        initial: 0,
        goal: 222,
        moves: 4,
        buttons: [insertRight(1), replace(1, 2)],
    },
    {
        initial: 0,
        goal: 93,
        moves: 4,
        buttons: [add(6), multiply(7), replace(6, 9)],
    },
    {
        initial: 0,
        goal: 2321,
        moves: 6,
        buttons: [insertRight(1), insertRight(2), replace(1, 2), replace(2, 3)],
    },
    {
        initial: 0,
        goal: 24,
        moves: 5,
        buttons: [add(9), multiply(2), replace(8, 4)],
    },
    {
        initial: 11,
        goal: 29,
        moves: 5,
        buttons: [add(3), divide(2), replace(1, 2), replace(2, 9)],
    },
    {
        initial: 36,
        goal: 20,
        moves: 5,
        buttons: [add(3), divide(3), replace(1, 2)],
    },
    {
        initial: 2,
        goal: 15,
        moves: 4,
        buttons: [multiply(2), divide(3), insertRight(1), replace(4, 5)],
    },
    {
        initial: 1234,
        goal: 414,
        moves: 4,
        buttons: [
            replace(23, 41),
            replace(24, 14),
            replace(12, 24),
            replace(14, 2),
        ],
    },
    {
        initial: 0,
        goal: -85,
        moves: 4,
        buttons: [add(6), subtract(7), insertRight(5)],
    },
    {
        initial: 0,
        goal: 9,
        moves: 3,
        buttons: [subtract(1), subtract(2), exponent(2)],
    },
    {
        initial: 0,
        goal: -120,
        moves: 4,
        buttons: [subtract(6), multiply(5), insertRight(4)],
    },
    {
        initial: 0,
        goal: 144,
        moves: 3,
        buttons: [subtract(1), insertRight(2), exponent(2)],
    },
    {
        initial: -5,
        goal: 5,
        moves: 1,
        buttons: [negate()],
    },
    {
        initial: 0,
        goal: -6,
        moves: 3,
        buttons: [add(2), add(4), negate()],
    },
    {
        initial: 0,
        goal: -13,
        moves: 4,
        buttons: [add(3), subtract(7), negate()],
    },
    {
        initial: 0,
        goal: 60,
        moves: 4,
        buttons: [add(5), subtract(10), multiply(4), negate()],
    },
    {
        initial: 44,
        goal: 52,
        moves: 5,
        buttons: [add(9), multiply(4), divide(2), negate()],
    },
    {
        initial: 9,
        goal: 10,
        moves: 5,
        buttons: [add(5), multiply(5), negate()],
    },
    {
        initial: 14,
        goal: 12,
        moves: 5,
        buttons: [add(5), divide(8), insertRight(6), negate()],
    },
    {
        initial: 55,
        goal: 13,
        moves: 4,
        buttons: [add(9), deleteRight(), negate()],
    },
    {
        initial: 0,
        goal: 245,
        moves: 5,
        buttons: [subtract(3), multiply(4), insertRight(5), negate()],
    },
    {
        initial: 39,
        goal: 12,
        moves: 4,
        buttons: [add(9), multiply(-3), divide(3), negate()],
    },
    {
        initial: 111,
        goal: 126,
        moves: 6,
        buttons: [subtract(9), multiply(3), deleteRight(), negate()],
    },
    {
        initial: 34,
        goal: 3,
        moves: 5,
        buttons: [add(8), subtract(5), divide(7), negate()],
    },
    {
        initial: 25,
        goal: 4,
        moves: 5,
        buttons: [subtract(4), multiply(-4), divide(3), divide(8)],
    },
    {
        initial: 12,
        goal: 21,
        moves: 1,
        buttons: [reverse()],
    },
    {
        initial: 0,
        goal: 51,
        moves: 3,
        buttons: [add(6), add(9), reverse()],
    },
    {
        initial: 100,
        goal: 101,
        moves: 3,
        buttons: [add(9), insertRight(1), reverse()],
    },
    {
        initial: 1101,
        goal: 100,
        moves: 4,
        buttons: [subtract(1), reverse()],
    },
    {
        initial: 0,
        goal: 58,
        moves: 4,
        buttons: [add(4), subtract(3), multiply(4), reverse()],
    },
    {
        initial: 6,
        goal: 4,
        moves: 3,
        buttons: [divide(4), insertRight(1), reverse()],
    },
    {
        initial: 15,
        goal: 21,
        moves: 3,
        buttons: [add(9), multiply(5), reverse()],
    },
    {
        initial: 100,
        goal: 13,
        moves: 5,
        buttons: [divide(2), reverse()],
    },
    {
        initial: 10,
        goal: 11011,
        moves: 4,
        buttons: [insertRight(1), reverse()],
    },
    {
        initial: 0,
        goal: 102,
        moves: 4,
        buttons: [add(5), multiply(4), insertRight(10), reverse()],
    },
    {
        initial: 0,
        goal: 7,
        moves: 4,
        buttons: [add(1), divide(3), insertRight(2), reverse()],
    },
    {
        initial: 0,
        goal: 4,
        moves: 4,
        buttons: [multiply(2), multiply(4), insertRight(5), reverse()],
    },
    {
        initial: 121,
        goal: 212,
        moves: 3,
        buttons: [subtract(1), insertRight(2), reverse()],
    },
    {
        initial: 8,
        goal: 9,
        moves: 5,
        buttons: [multiply(3), divide(5), insertRight(1), reverse()],
    },
    {
        initial: 0,
        goal: 13,
        moves: 5,
        buttons: [add(7), add(8), add(9), reverse()],
    },
    {
        initial: 0,
        goal: 123,
        moves: 6,
        buttons: [add(3), subtract(2), insertRight(1), reverse()],
    },
    {
        initial: 0,
        goal: 424,
        moves: 5,
        buttons: [add(8), insertRight(6), reverse()],
    },
    {
        initial: 7,
        goal: 81,
        moves: 5,
        buttons: [add(4), subtract(9), multiply(3), negate(), reverse()],
    },
    {
        initial: 0,
        goal: -43,
        moves: 5,
        buttons: [add(7), subtract(5), subtract(9), reverse()],
    },
    {
        initial: 0,
        goal: 28,
        moves: 7,
        buttons: [add(6), subtract(3), deleteRight(), reverse()],
    },
    {
        initial: 0,
        goal: 136,
        moves: 5,
        buttons: [add(2), multiply(3), insertRight(1), reverse()],
    },
    {
        initial: 0,
        goal: -1,
        moves: 4,
        buttons: [add(5), negate(), reverse()],
    },
    {
        initial: 0,
        goal: -25,
        moves: 5,
        buttons: [add(4), multiply(3), negate(), reverse()],
    },
    {
        initial: 0,
        goal: -5,
        moves: 5,
        buttons: [add(7), multiply(3), negate(), reverse()],
    },
    {
        initial: 88,
        goal: 41,
        moves: 4,
        buttons: [subtract(4), divide(4), reverse()],
    },
    {
        initial: 100,
        goal: 101,
        moves: 5,
        buttons: [
            multiply(2),
            insertRight(0),
            replace(2, 10),
            replace(0, 1),
            reverse(),
        ],
    },
    {
        initial: 0,
        goal: 424,
        moves: 7,
        buttons: [divide(2), insertRight(5), replace(5, 4), reverse()],
    },
    {
        initial: 99,
        goal: 100,
        moves: 5,
        buttons: [divide(9), insertRight(9), replace(1, 0), reverse()],
    },
    {
        initial: 8,
        goal: 30,
        moves: 5,
        buttons: [subtract(4), insertRight(2), replace(2, 3), reverse()],
    },
    {
        initial: 101,
        goal: 222,
        moves: 5,
        buttons: [subtract(1), replace(0, 2), reverse()],
    },
    {
        initial: 36,
        goal: 500,
        moves: 5,
        buttons: [multiply(4), divide(3), replace(1, 5), reverse()],
    },
    {
        initial: 0,
        goal: 196,
        moves: 8,
        buttons: [
            add(12),
            multiply(13),
            insertRight(1),
            deleteRight(),
            reverse(),
        ],
    },
    {
        initial: 50,
        goal: 101,
        moves: 5,
        buttons: [add(50), replace(1, 10), replace(5, 1), reverse()],
    },
    {
        initial: 1,
        goal: 2048,
        moves: 6,
        buttons: [multiply(4), multiply(10), insertRight(2), reverse()],
    },
    {
        initial: 12,
        goal: 123,
        moves: 5,
        buttons: [add(1), insertRight(12), replace(12, 2), reverse()],
    },
    {
        initial: 86,
        goal: 55,
        moves: 6,
        buttons: [add(2), add(14), replace(0, 5), reverse()],
    },
    {
        initial: 0,
        goal: 3,
        moves: 4,
        buttons: [insertRight(1), sumDigits()],
    },
    {
        initial: 1231,
        goal: 4,
        moves: 3,
        buttons: [replace(3, 1), replace(2, 3), sumDigits()],
    },
    {
        initial: 0,
        goal: 45,
        moves: 5,
        buttons: [
            multiply(3),
            multiply(9),
            insertRight(4),
            replace(3, 5),
            sumDigits(),
        ],
    },
    {
        initial: 424,
        goal: 28,
        moves: 5,
        buttons: [multiply(4), replace(4, 6), sumDigits()],
    },
    {
        initial: 3,
        goal: 8,
        moves: 4,
        buttons: [add(33), insertRight(3), replace(3, 1), sumDigits()],
    },
    {
        initial: 24,
        goal: 44,
        moves: 4,
        buttons: [divide(2), insertRight(4), replace(1, 2), sumDigits()],
    },
    {
        initial: 142,
        goal: 143,
        moves: 4,
        buttons: [add(9), multiply(9), replace(44, 43), sumDigits()],
    },
    {
        initial: 24,
        goal: 1,
        moves: 5,
        buttons: [multiply(4), divide(3), replace(5, 10), sumDigits()],
    },
    {
        initial: 4,
        goal: 100,
        moves: 5,
        buttons: [add(1), multiply(3), insertRight(3), sumDigits()],
    },
    {
        initial: 93,
        goal: 8,
        moves: 5,
        buttons: [add(4), multiply(3), sumDigits()],
    },
    {
        initial: 5,
        goal: 16,
        moves: 5,
        buttons: [multiply(5), divide(2), replace(5, 2), sumDigits()],
    },
    {
        initial: 128,
        goal: 64,
        moves: 4,
        buttons: [multiply(4), divide(4), replace(5, 16), sumDigits()],
    },
    {
        initial: 59,
        goal: 121,
        moves: 6,
        buttons: [multiply(5), insertRight(1), replace(15, 51), sumDigits()],
    },
    {
        initial: 18,
        goal: 5,
        moves: 6,
        buttons: [multiply(2), divide(3), replace(12, 21), sumDigits()],
    },
    {
        initial: 9,
        goal: 30,
        moves: 4,
        buttons: [subtract(5), multiply(-6), negate(), sumDigits()],
    },
    {
        initial: 105,
        goal: -17,
        moves: 5,
        buttons: [subtract(5), multiply(4), divide(5), negate(), sumDigits()],
    },
    {
        initial: 36,
        goal: 11,
        moves: 6,
        buttons: [subtract(6), divide(3), negate(), sumDigits()],
    },
    {
        initial: 3,
        goal: 64,
        moves: 5,
        buttons: [add(3), replace(0, 1), exponent(3), sumDigits()],
    },
    {
        initial: 2,
        goal: 11,
        moves: 5,
        buttons: [
            multiply(2),
            insertRight(10),
            replace(10, 1),
            exponent(3),
            sumDigits(),
        ],
    },
    {
        initial: 1123,
        goal: 2311,
        moves: 2,
        buttons: [cycleLeft()],
    },
    {
        initial: 5432,
        goal: 3254,
        moves: 2,
        buttons: [cycleRight()],
    },
    {
        initial: 101,
        goal: 121,
        moves: 3,
        buttons: [add(2), cycleLeft(), cycleRight()],
    },
    {
        initial: 98,
        goal: 1999,
        moves: 4,
        buttons: [
            insertRight(1),
            insertRight(9),
            replace(89, 99),
            cycleRight(),
        ],
    },
    {
        initial: 70,
        goal: 129,
        moves: 4,
        buttons: [multiply(3), insertRight(9), cycleRight()],
    },
    {
        initial: 120,
        goal: 210,
        moves: 5,
        buttons: [add(1), negate(), cycleLeft()],
    },
    {
        initial: 1001,
        goal: 210,
        moves: 5,
        buttons: [add(2), replace(12, 0), cycleRight()],
    },
    {
        initial: 100,
        goal: 501,
        moves: 3,
        buttons: [add(5), insertRight(0), cycleLeft()],
    },
    {
        initial: 212,
        goal: 3,
        moves: 4,
        buttons: [add(11), replace(3, 1), sumDigits(), cycleLeft()],
    },
    {
        initial: 356,
        goal: 121,
        moves: 4,
        buttons: [subtract(2), divide(3), cycleRight()],
    },
    {
        initial: 2152,
        goal: 13,
        moves: 6,
        buttons: [
            replace(25, 12),
            replace(21, 3),
            replace(12, 5),
            reverse(),
            cycleRight(),
        ],
    },
    {
        initial: 1025,
        goal: 520,
        moves: 5,
        buttons: [
            replace(50, 0),
            replace(25, 525),
            replace(51, 5),
            cycleRight(),
        ],
    },
    {
        initial: 23,
        goal: 2332,
        moves: 1,
        buttons: [mirror()],
    },
    {
        initial: 0,
        goal: 1221,
        moves: 3,
        buttons: [insertRight(1), insertRight(2), mirror()],
    },
    {
        initial: 91,
        goal: 19,
        moves: 6,
        buttons: [add(5), sumDigits(), mirror()],
    },
    {
        initial: 22,
        goal: 116,
        moves: 4,
        buttons: [subtract(3), insertRight(6), sumDigits(), mirror()],
    },
    {
        initial: 125,
        goal: 20,
        moves: 7,
        buttons: [insertRight(0), replace(6, 2), sumDigits(), mirror()],
    },
    {
        initial: 22,
        goal: 3,
        moves: 4,
        buttons: [divide(2), deleteRight(), sumDigits(), mirror()],
    },
    {
        initial: 0,
        goal: 1111,
        moves: 5,
        buttons: [add(2), multiply(6), replace(21, 11), mirror()],
    },
    {
        initial: -1,
        goal: 2020,
        moves: 8,
        buttons: [add(2), add(8), multiply(3), reverse(), mirror()],
    },
    {
        initial: 13,
        goal: 112,
        moves: 6,
        buttons: [
            multiply(3),
            divide(3),
            replace(99, 60),
            cycleRight(),
            mirror(),
        ],
    },
    {
        initial: 140,
        goal: 18,
        moves: 6,
        buttons: [add(9), subtract(3), divide(12), deleteRight(), mirror()],
    },
    {
        initial: 17,
        goal: 33,
        moves: 4,
        buttons: [subtract(4), multiply(2), cycleLeft(), mirror()],
    },
    {
        initial: 125,
        goal: 20,
        moves: 8,
        buttons: [sumDigits(), mirror()],
    },
    {
        initial: 10,
        goal: 15,
        moves: 3,
        buttons: [add(2), addButtonValue(1)],
    },
    {
        initial: 0,
        goal: 14,
        moves: 4,
        buttons: [add(2), insertRight(1), addButtonValue(1)],
    },
    {
        initial: 0,
        goal: 34,
        moves: 3,
        buttons: [insertRight(2), insertRight(3), addButtonValue(1)],
    },
    {
        initial: 0,
        goal: 101,
        moves: 5,
        buttons: [add(5), insertRight(2), addButtonValue(2)],
    },
    {
        initial: 0,
        goal: 28,
        moves: 5,
        buttons: [add(2), insertRight(1), addButtonValue(3)],
    },
    {
        initial: 0,
        goal: 42,
        moves: 5,
        buttons: [add(5), subtract(1), multiply(2), addButtonValue(1)],
    },
    {
        initial: 0,
        goal: 25,
        moves: 5,
        buttons: [add(2), subtract(3), multiply(3), addButtonValue(2)],
    },
    {
        initial: 5,
        goal: 41,
        moves: 4,
        buttons: [add(4), add(8), multiply(3), addButtonValue(2)],
    },
    {
        initial: 33,
        goal: 31,
        moves: 5,
        buttons: [add(2), add(3), multiply(4), sumDigits(), addButtonValue(1)],
    },
    {
        initial: 25,
        goal: 268,
        moves: 5,
        buttons: [add(8), multiply(2), multiply(5), addButtonValue(1)],
    },
    {
        initial: 1,
        goal: 1111,
        moves: 4,
        buttons: [...store()],
    },
    {
        initial: 0,
        goal: 121,
        moves: 5,
        buttons: [add(1), ...store()],
    },
    {
        initial: 12,
        goal: 122,
        moves: 5,
        buttons: [deleteRight(), reverse(), ...store()],
    },
    {
        initial: 10,
        goal: 17,
        moves: 6,
        buttons: [add(2), divide(3), reverse(), ...store()],
    },
    {
        initial: 23,
        goal: 1234,
        moves: 5,
        buttons: [subtract(5), multiply(2), cycleLeft(), ...store()],
    },
    {
        initial: 125,
        goal: 1025,
        moves: 7,
        buttons: [multiply(2), deleteRight(), ...store()],
    },
    {
        initial: 23,
        goal: 115,
        moves: 6,
        buttons: [subtract(8), negate(), ...store()],
    },
    {
        initial: 15,
        goal: 16,
        moves: 5,
        buttons: [replace(11, 33), reverse(), sumDigits(), ...store()],
    },
    {
        initial: 0,
        goal: 61,
        moves: 8,
        buttons: [insertRight(5), deleteRight(), sumDigits(), ...store()],
    },
    {
        initial: 0,
        goal: 101,
        moves: 6,
        buttons: [
            multiply(6),
            insertRight(5),
            replace(3, 1),
            cycleRight(),
            ...store(),
        ],
    },
    {
        initial: 125,
        goal: 12525,
        moves: 6,
        buttons: [divide(5), insertRight(1), reverse(), ...store()],
    },
    {
        initial: 70,
        goal: 17,
        moves: 7,
        buttons: [
            divide(2),
            insertRight(0),
            replace(8, 1),
            sumDigits(),
            ...store(),
        ],
    },
    {
        initial: 12,
        goal: 101,
        moves: 5,
        buttons: [replace(12, 1), replace(21, 0), mirror(), ...store()],
    },
    {
        initial: 9,
        goal: 3001,
        moves: 9,
        buttons: [divide(3), replace(39, 93), replace(31, "00"), ...store()],
    },
    {
        initial: 0,
        goal: 99,
        moves: 3,
        buttons: [insertRight(1), inv10()],
    },
    {
        initial: 1,
        goal: 2,
        moves: 3,
        buttons: [subtract(1), inv10()],
    },
    {
        initial: 14,
        goal: 15,
        moves: 3,
        buttons: [add(5), multiply(5), inv10()],
    },
    {
        initial: 21,
        goal: 12,
        moves: 3,
        buttons: [subtract(7), multiply(5), inv10()],
    },
    {
        initial: 67,
        goal: 13,
        moves: 4,
        buttons: [add(3), reverse(), inv10()],
    },
    {
        initial: 23,
        goal: 88,
        moves: 5,
        buttons: [subtract(2), subtract(4), reverse(), inv10()],
    },
    {
        initial: 5,
        goal: 105,
        moves: 5,
        buttons: [multiply(3), divide(9), ...store(), inv10()],
    },
    {
        initial: 24,
        goal: 23,
        moves: 4,
        buttons: [add(6), multiply(3), reverse(), inv10()],
    },
    {
        initial: 7,
        goal: 17,
        moves: 4,
        buttons: [add(3), multiply(3), multiply(4), inv10()],
    },
    {
        initial: 35,
        goal: 21,
        moves: 5,
        buttons: [multiply(9), divide(5), replace(13, 10), inv10()],
    },
    {
        initial: 9,
        goal: 18,
        moves: 5,
        buttons: [multiply(3), sumDigits(), inv10()],
    },
    {
        initial: 12,
        goal: 101,
        moves: 5,
        buttons: [add(4), sumDigits(), inv10()],
    },
    {
        initial: 26,
        goal: 99,
        moves: 6,
        buttons: [insertRight(2), sumDigits(), inv10()],
    },
    {
        initial: 15,
        goal: 13,
        moves: 7,
        buttons: [sumDigits(), mirror(), inv10()],
    },
    {
        initial: 78,
        goal: 99,
        moves: 6,
        buttons: [divide(6), replace(1, 6), replace(6, 11), reverse(), inv10()],
    },
    {
        initial: 34,
        goal: 9,
        moves: 4,
        buttons: [multiply(6), deleteRight(), inv10()],
    },
    {
        initial: 0,
        goal: 872,
        moves: 8,
        buttons: [insertRight(8), replace(88, 34), deleteRight(), inv10()],
    },
    {
        initial: 5,
        goal: 33,
        moves: 5,
        buttons: [add(8), subtract(9), multiply(2), multiply(7), inv10()],
    },
    {
        initial: 12,
        goal: 23,
        moves: 7,
        buttons: [multiply(5), sumDigits(), ...store(), inv10()],
    },
    {
        initial: 1,
        goal: 1991,
        moves: 6,
        buttons: [...store(), inv10()],
    },
    {
        initial: 12,
        goal: 26,
        moves: 5,
        buttons: [deleteRight(), sumDigits(), ...store(), inv10()],
    },
    {
        initial: 51,
        goal: 48,
        moves: 6,
        buttons: [add(6), multiply(3), replace(4, 6), reverse(), inv10()],
    },
    {
        initial: 0,
        goal: 1,
        moves: 6,
        buttons: [add(5), multiply(3), divide(6), reverse(), inv10()],
    },
    {
        initial: 369,
        goal: 777,
        moves: 5,
        buttons: [
            replace(93, 63),
            replace(63, 33),
            replace(36, 93),
            replace(39, 33),
            inv10(),
        ],
    },
    {
        initial: 99,
        goal: 10,
        moves: 3,
        buttons: [subtract(1), insertRight(1)],
        portalPos: [3, 1],
    },
    {
        initial: 9,
        goal: 64,
        moves: 2,
        buttons: [insertRight(4), insertRight(6)],
        portalPos: [3, 2],
    },
    {
        initial: 50,
        goal: 35,
        moves: 3,
        buttons: [add(5), multiply(3), multiply(5)],
        portalPos: [3, 2],
    },
    {
        initial: 306,
        goal: 131,
        moves: 4,
        buttons: [add(1), multiply(2), insertRight(3)],
        portalPos: [4, 1],
    },
    {
        initial: 321,
        goal: 123,
        moves: 5,
        buttons: [divide(2), insertRight(0), insertRight(1), insertRight(3)],
        portalPos: [4, 1],
    },
];

const LEVELS_MINIPLAY: Level[] = [
    {
        initial: 0,
        goal: 2,
        moves: 2,
        buttons: [add(1)],
    },
    {
        initial: 0,
        goal: 8,
        moves: 3,
        buttons: [add(2), add(3)],
    },
    {
        initial: 0,
        goal: 9,
        moves: 3,
        buttons: [add(1), add(2), multiply(3)],
    },
    {
        initial: 1,
        goal: 7,
        moves: 3,
        buttons: [add(4), subtract(2)],
    },
    {
        initial: 3,
        goal: 4,
        moves: 3,
        buttons: [add(4), multiply(4), divide(4)],
    },
    {
        initial: 0,
        goal: 64,
        moves: 4,
        buttons: [add(2), multiply(4)],
    },
    {
        initial: 4,
        goal: 5,
        moves: 3,
        buttons: [add(3), multiply(3), divide(3)],
    },
    {
        initial: 0,
        goal: 48,
        moves: 4,
        buttons: [add(8), multiply(4)],
    },
    {
        initial: 800,
        goal: 100,
        moves: 3,
        buttons: [multiply(2), divide(4)],
    },
    {
        initial: 0,
        goal: 404,
        moves: 5,
        buttons: [add(8), multiply(10), divide(2)],
    },
    {
        initial: 10,
        goal: 100,
        moves: 4,
        buttons: [subtract(5), multiply(2), multiply(3)],
    },
    {
        initial: 0,
        goal: 4,
        moves: 3,
        buttons: [add(8), multiply(5), deleteRight()],
    },
    {
        initial: 50,
        goal: 9,
        moves: 4,
        buttons: [multiply(3), divide(5), deleteRight()],
    },
    {
        initial: 99,
        goal: 100,
        moves: 3,
        buttons: [subtract(8), multiply(11), deleteRight()],
    },
    {
        initial: 171,
        goal: 23,
        moves: 4,
        buttons: [subtract(9), multiply(2), deleteRight()],
    },
    {
        initial: 0,
        goal: 24,
        moves: 6,
        buttons: [add(5), multiply(3), multiply(5), deleteRight()],
    },
    {
        initial: 0,
        goal: 2,
        moves: 5,
        buttons: [add(4), multiply(9), deleteRight()],
    },
    {
        initial: 0,
        goal: 11,
        moves: 2,
        buttons: [insertRight(1)],
    },
    {
        initial: 0,
        goal: 101,
        moves: 3,
        buttons: [insertRight(0), insertRight(1)],
    },
    {
        initial: 0,
        goal: 44,
        moves: 3,
        buttons: [multiply(2), insertRight(2)],
    },
    {
        initial: 0,
        goal: 35,
        moves: 2,
        buttons: [add(3), insertRight(5)],
    },
    {
        initial: 0,
        goal: 56,
        moves: 3,
        buttons: [add(5), insertRight(1)],
    },
    {
        initial: 0,
        goal: 9,
        moves: 4,
        buttons: [add(2), divide(3), insertRight(1)],
    },
    {
        initial: 15,
        goal: 10,
        moves: 4,
        buttons: [add(2), divide(5), insertRight(0)],
    },
    {
        initial: 0,
        goal: 210,
        moves: 5,
        buttons: [add(5), subtract(5), insertRight(2), insertRight(5)],
    },
    {
        initial: 4,
        goal: 2020,
        moves: 5,
        buttons: [add(4), divide(2), insertRight(0)],
    },
    {
        initial: 0,
        goal: 11,
        moves: 4,
        buttons: [insertRight(12), deleteRight()],
    },
    {
        initial: 0,
        goal: 102,
        moves: 4,
        buttons: [add(1), insertRight(10), deleteRight()],
    },
    {
        initial: 0,
        goal: 222,
        moves: 4,
        buttons: [insertRight(1), replace(1, 2)],
    },
    {
        initial: 0,
        goal: 93,
        moves: 4,
        buttons: [add(6), multiply(7), replace(6, 9)],
    },
    {
        initial: 0,
        goal: 2321,
        moves: 6,
        buttons: [insertRight(1), insertRight(2), replace(1, 2), replace(2, 3)],
    },
    {
        initial: 0,
        goal: 24,
        moves: 5,
        buttons: [add(9), multiply(2), replace(8, 4)],
    },
    {
        initial: 11,
        goal: 29,
        moves: 5,
        buttons: [add(3), divide(2), replace(1, 2), replace(2, 9)],
    },
    {
        initial: 36,
        goal: 20,
        moves: 5,
        buttons: [add(3), divide(3), replace(1, 2)],
    },
    {
        initial: 2,
        goal: 15,
        moves: 4,
        buttons: [multiply(2), divide(3), insertRight(1), replace(4, 5)],
    },
    {
        initial: 1234,
        goal: 414,
        moves: 4,
        buttons: [
            replace(23, 41),
            replace(24, 14),
            replace(12, 24),
            replace(14, 2),
        ],
    },
    {
        initial: 0,
        goal: -85,
        moves: 4,
        buttons: [add(6), subtract(7), insertRight(5)],
    },
    {
        initial: 0,
        goal: 9,
        moves: 3,
        buttons: [subtract(1), subtract(2), exponent(2)],
    },
    {
        initial: 0,
        goal: -120,
        moves: 4,
        buttons: [subtract(6), multiply(5), insertRight(4)],
    },
    {
        initial: 0,
        goal: 144,
        moves: 3,
        buttons: [subtract(1), insertRight(2), exponent(2)],
    },
    {
        initial: 0,
        goal: -6,
        moves: 3,
        buttons: [add(2), add(4), negate()],
    },
    {
        initial: 0,
        goal: -13,
        moves: 4,
        buttons: [add(3), subtract(7), negate()],
    },
    {
        initial: 0,
        goal: 60,
        moves: 4,
        buttons: [add(5), subtract(10), multiply(4), negate()],
    },
    {
        initial: 44,
        goal: 52,
        moves: 5,
        buttons: [add(9), divide(2), multiply(4), negate()],
    },
    {
        initial: 9,
        goal: 10,
        moves: 5,
        buttons: [add(5), multiply(5), negate()],
    },
    {
        initial: 14,
        goal: 12,
        moves: 5,
        buttons: [add(5), divide(8), insertRight(6), negate()],
    },
    {
        initial: 55,
        goal: 13,
        moves: 4,
        buttons: [add(9), negate(), deleteRight()],
    },
    {
        initial: 0,
        goal: 245,
        moves: 5,
        buttons: [subtract(3), multiply(4), insertRight(5), negate()],
    },
    {
        initial: 39,
        goal: 12,
        moves: 4,
        buttons: [add(9), multiply(-3), divide(3), negate()],
    },
    {
        initial: 111,
        goal: 126,
        moves: 6,
        buttons: [subtract(9), multiply(3), deleteRight(), negate()],
    },
    {
        initial: 34,
        goal: 3,
        moves: 5,
        buttons: [add(8), subtract(5), divide(7), negate()],
    },
    {
        initial: 25,
        goal: 4,
        moves: 5,
        buttons: [subtract(4), multiply(-4), divide(3), divide(8)],
    },
    {
        initial: 0,
        goal: 51,
        moves: 3,
        buttons: [add(6), add(9), reverse()],
    },
    {
        initial: 100,
        goal: 101,
        moves: 3,
        buttons: [add(9), insertRight(1), reverse()],
    },
    {
        initial: 1101,
        goal: 100,
        moves: 4,
        buttons: [subtract(1), reverse()],
    },
    {
        initial: 0,
        goal: 58,
        moves: 4,
        buttons: [add(4), subtract(3), multiply(4), reverse()],
    },
    {
        initial: 6,
        goal: 4,
        moves: 3,
        buttons: [divide(4), insertRight(1), reverse()],
    },
    {
        initial: 15,
        goal: 21,
        moves: 3,
        buttons: [add(9), multiply(5), reverse()],
    },
    {
        initial: 100,
        goal: 13,
        moves: 5,
        buttons: [divide(2), reverse()],
    },
    {
        initial: 10,
        goal: 11011,
        moves: 4,
        buttons: [insertRight(1), reverse()],
    },
    {
        initial: 0,
        goal: 102,
        moves: 4,
        buttons: [add(5), multiply(4), insertRight(10), reverse()],
    },
    {
        initial: 0,
        goal: 7,
        moves: 4,
        buttons: [add(1), divide(3), insertRight(2), reverse()],
    },
    {
        initial: 0,
        goal: 4,
        moves: 4,
        buttons: [multiply(4), multiply(2), insertRight(5), reverse()],
    },
    {
        initial: 121,
        goal: 212,
        moves: 3,
        buttons: [subtract(1), insertRight(2), reverse()],
    },
    {
        initial: 8,
        goal: 9,
        moves: 5,
        buttons: [multiply(3), divide(5), insertRight(1), reverse()],
    },
    {
        initial: 0,
        goal: 13,
        moves: 5,
        buttons: [add(9), add(8), add(7), reverse()],
    },
    {
        initial: 0,
        goal: 123,
        moves: 6,
        buttons: [add(3), subtract(2), insertRight(1), reverse()],
    },
    {
        initial: 0,
        goal: 424,
        moves: 5,
        buttons: [add(8), insertRight(6), reverse()],
    },
    {
        initial: 7,
        goal: 81,
        moves: 5,
        buttons: [add(4), multiply(3), subtract(9), negate(), reverse()],
    },
    {
        initial: 0,
        goal: -43,
        moves: 5,
        buttons: [add(7), subtract(5), subtract(9), reverse()],
    },
    {
        initial: 0,
        goal: 28,
        moves: 7,
        buttons: [add(6), subtract(3), reverse(), deleteRight()],
    },
    {
        initial: 0,
        goal: 136,
        moves: 5,
        buttons: [add(2), multiply(3), insertRight(1), reverse()],
    },
    {
        initial: 0,
        goal: -1,
        moves: 4,
        buttons: [add(5), negate(), reverse()],
    },
    {
        initial: 0,
        goal: -25,
        moves: 5,
        buttons: [add(4), multiply(3), negate(), reverse()],
    },
    {
        initial: 0,
        goal: -5,
        moves: 5,
        buttons: [add(7), multiply(3), negate(), reverse()],
    },
    {
        initial: 88,
        goal: 41,
        moves: 4,
        buttons: [subtract(4), divide(4), reverse()],
    },
    {
        initial: 100,
        goal: 101,
        moves: 5,
        buttons: [
            multiply(2),
            insertRight(0),
            replace(2, 10),
            replace(0, 1),
            reverse(),
        ],
    },
    {
        initial: 0,
        goal: 424,
        moves: 7,
        buttons: [divide(2), insertRight(5), replace(5, 4), reverse()],
    },
    {
        initial: 99,
        goal: 100,
        moves: 5,
        buttons: [divide(9), insertRight(9), replace(1, 0), reverse()],
    },
    {
        initial: 8,
        goal: 30,
        moves: 5,
        buttons: [subtract(4), insertRight(2), replace(2, 3)],
    },
    {
        initial: 101,
        goal: 222,
        moves: 5,
        buttons: [subtract(1), replace(0, 2), reverse()],
    },
    {
        initial: 36,
        goal: 500,
        moves: 5,
        buttons: [multiply(4), divide(3), replace(1, 5), reverse()],
    },
    {
        initial: 0,
        goal: 196,
        moves: 8,
        buttons: [
            add(12),
            multiply(13),
            insertRight(1),
            deleteRight(),
            reverse(),
        ],
    },
    {
        initial: 50,
        goal: 101,
        moves: 5,
        buttons: [add(50), replace(1, 10), replace(5, 1), reverse()],
    },
    {
        initial: 1,
        goal: 2048,
        moves: 6,
        buttons: [multiply(4), multiply(10), insertRight(2), reverse()],
    },
    {
        initial: 12,
        goal: 123,
        moves: 5,
        buttons: [add(1), insertRight(12), replace(12, 2), reverse()],
    },
    {
        initial: 86,
        goal: 55,
        moves: 6,
        buttons: [add(2), add(14), replace(0, 5), reverse()],
    },
    {
        initial: 0,
        goal: 3,
        moves: 4,
        buttons: [insertRight(1), sumDigits()],
    },
    {
        initial: 1231,
        goal: 4,
        moves: 3,
        buttons: [replace(2, 3), replace(3, 1), sumDigits()],
    },
    {
        initial: 0,
        goal: 45,
        moves: 5,
        buttons: [
            multiply(3),
            multiply(9),
            insertRight(4),
            replace(3, 5),
            sumDigits(),
        ],
    },
    {
        initial: 424,
        goal: 28,
        moves: 5,
        buttons: [multiply(4), replace(4, 6), sumDigits()],
    },
    {
        initial: 3,
        goal: 8,
        moves: 4,
        buttons: [add(33), insertRight(3), replace(3, 1), sumDigits()],
    },
    {
        initial: 24,
        goal: 44,
        moves: 4,
        buttons: [divide(2), insertRight(4), replace(1, 2), sumDigits()],
    },
    {
        initial: 142,
        goal: 143,
        moves: 4,
        buttons: [add(9), multiply(9), replace(44, 43), sumDigits()],
    },
    {
        initial: 24,
        goal: 1,
        moves: 5,
        buttons: [multiply(4), divide(3), replace(5, 10), sumDigits()],
    },
    {
        initial: 4,
        goal: 100,
        moves: 5,
        buttons: [add(1), multiply(3), insertRight(3), sumDigits()],
    },
    {
        initial: 93,
        goal: 8,
        moves: 5,
        buttons: [add(4), multiply(3), sumDigits()],
    },
    {
        initial: 5,
        goal: 16,
        moves: 5,
        buttons: [multiply(5), divide(2), replace(5, 2), sumDigits()],
    },
    {
        initial: 128,
        goal: 64,
        moves: 4,
        buttons: [multiply(4), divide(4), replace(5, 16), sumDigits()],
    },
    {
        initial: 59,
        goal: 121,
        moves: 6,
        buttons: [multiply(5), insertRight(1), replace(15, 51), sumDigits()],
    },
    {
        initial: 18,
        goal: 5,
        moves: 6,
        buttons: [multiply(2), divide(3), replace(12, 21), sumDigits()],
    },
    {
        initial: 9,
        goal: 30,
        moves: 4,
        buttons: [subtract(5), multiply(-6), negate(), sumDigits()],
    },
    {
        initial: 105,
        goal: -17,
        moves: 5,
        buttons: [subtract(5), multiply(4), divide(5), negate(), sumDigits()],
    },
    {
        initial: 36,
        goal: 11,
        moves: 6,
        buttons: [subtract(6), divide(3), negate(), sumDigits()],
    },
    {
        initial: 3,
        goal: 64,
        moves: 5,
        buttons: [add(3), replace(0, 1), sumDigits(), exponent(3)],
    },
    {
        initial: 2,
        goal: 11,
        moves: 5,
        buttons: [
            multiply(2),
            insertRight(10),
            exponent(3),
            replace(10, 1),
            sumDigits(),
        ],
    },
    {
        initial: 1123,
        goal: 2311,
        moves: 2,
        buttons: [cycleLeft()],
    },
    {
        initial: 5432,
        goal: 3254,
        moves: 2,
        buttons: [cycleRight()],
    },
    {
        initial: 101,
        goal: 121,
        moves: 3,
        buttons: [add(2), cycleLeft(), cycleRight()],
    },
    {
        initial: 98,
        goal: 1999,
        moves: 4,
        buttons: [
            insertRight(1),
            insertRight(9),
            replace(89, 99),
            cycleRight(),
        ],
    },
    {
        initial: 7,
        goal: 129,
        moves: 3,
        buttons: [multiply(3), insertRight(9), cycleRight()],
    },
    {
        initial: 120,
        goal: 210,
        moves: 5,
        buttons: [add(1), cycleLeft(), negate()],
    },
    {
        initial: 1001,
        goal: 210,
        moves: 5,
        buttons: [add(2), cycleRight(), replace(12, 0)],
    },
    {
        initial: 100,
        goal: 501,
        moves: 3,
        buttons: [add(5), insertRight(0), cycleLeft()],
    },
    {
        initial: 212,
        goal: 3,
        moves: 4,
        buttons: [add(11), replace(3, 1), cycleLeft(), sumDigits()],
    },
    {
        initial: 356,
        goal: 121,
        moves: 4,
        buttons: [subtract(2), divide(3), cycleRight()],
    },
    {
        initial: 2152,
        goal: 13,
        moves: 6,
        buttons: [
            replace(25, 12),
            replace(21, 3),
            replace(12, 5),
            reverse(),
            cycleRight(),
        ],
    },
    {
        initial: 1025,
        goal: 520,
        moves: 5,
        buttons: [
            replace(50, 0),
            replace(25, 525),
            replace(51, 5),
            cycleRight(),
        ],
    },
    {
        initial: 23,
        goal: 2332,
        moves: 1,
        buttons: [mirror()],
    },
    {
        initial: 0,
        goal: 1221,
        moves: 3,
        buttons: [insertRight(1), insertRight(2), mirror()],
    },
    {
        initial: 91,
        goal: 19,
        moves: 6,
        buttons: [add(5), mirror(), sumDigits()],
    },
    {
        initial: 22,
        goal: 116,
        moves: 4,
        buttons: [subtract(3), insertRight(6), mirror(), sumDigits()],
    },
    {
        initial: 125,
        goal: 20,
        moves: 7,
        buttons: [insertRight(0), replace(6, 2), mirror(), sumDigits()],
    },
    {
        initial: 22,
        goal: 3,
        moves: 4,
        buttons: [divide(2), sumDigits(), mirror(), deleteRight()],
    },
    {
        initial: 0,
        goal: 1111,
        moves: 5,
        buttons: [add(2), multiply(6), replace(21, 11), mirror()],
    },
    {
        initial: -1,
        goal: 2020,
        moves: 8,
        buttons: [add(2), add(8), multiply(3), reverse(), mirror()],
    },
    {
        initial: 13,
        goal: 112,
        moves: 6,
        buttons: [
            multiply(3),
            divide(3),
            replace(99, 60),
            mirror(),
            cycleRight(),
        ],
    },
    {
        initial: 140,
        goal: 18,
        moves: 6,
        buttons: [add(9), subtract(3), divide(12), mirror(), deleteRight()],
    },
    {
        initial: 17,
        goal: 33,
        moves: 4,
        buttons: [subtract(4), multiply(2), mirror(), deleteRight()],
    },
    {
        initial: 125,
        goal: 20,
        moves: 8,
        buttons: [mirror(), sumDigits()],
    },
];

export const LEVELS = {
    simple_machine: LEVELS_SIMPLE_MACHINE,
    miniplay: LEVELS_MINIPLAY,
};
export type { Level };
